[project]
name = "semantic-layer-duckdb"
version = "0.1.0"
description = "Trying boring semantic layer with DuckDB"
requires-python = ">=3.13,<3.14"
dependencies = [
    "PyYAML",
    "boring-semantic-layer",
    "boring-semantic-layer[visualization]",
    "altair[all]",
]